version: "3.9"

services:
  # supabase:
  #   image: supabase/supabase
  #   ports:
  #     - "54321:54321"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chijji-moni-app

    ports:
      - "8080:8080"

    working_dir: /chijji-moni

    restart: unless-stopped
