version: '3'

vars:
  BIN_NAME: app
  EXT: '{{if eq OS "windows"}}.exe{{end}}'
  DIR: '{{if eq OS "windows"}}windows{{else}}linux{{end}}'

tasks:
  build:
    dir: app
    cmds:
      - go build -o ../dist/{{.BIN_NAME}}{{.EXT}}
  dev:
    dir: app
    cmds:
      - air
  start:
    dir: dist
    cmds:
      - cp ../.env .env 
      - ./{{.BIN_NAME}}{{.EXT}}
    
  run:
    cmds: 
      - task build
      - task start